apiVersion: v1
kind: Secret
metadata:
  name: deployer-secrets
  namespace: deployer
type: Opaque
stringData:
  DATABASE_URL: "postgres://deployer:deployer_prod_2024@postgres:5432/deployer?sslmode=disable"
  REDIS_URL: "redis://redis:6379"
  JWT_SECRET: "deployer-jwt-secret-prod-2024-change-me"
  REGISTRY_URL: "https://registry.sviniabanditka.com"
