FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/worker ./cmd/worker

FROM alpine:3.21
RUN apk add --no-cache ca-certificates tzdata docker-cli git
# Install nixpacks
RUN wget -qO- https://github.com/railwayapp/nixpacks/releases/latest/download/nixpacks-linux-amd64.tar.gz | tar xz -C /usr/local/bin
COPY --from=builder /bin/worker /bin/worker
CMD ["/bin/worker"]
